name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/html-demo:latest .
      
    - name: Push to GHCR
      run: docker push ghcr.io/${{ github.repository }}/html-demo:latest
      
    - name: Thông báo thành công
      run: echo "✅ Đã push image thành công!"